// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "awgn_top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic awgn_top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic awgn_top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> awgn_top::ap_ST_fsm_state1 = "1";
const sc_lv<3> awgn_top::ap_ST_fsm_state2 = "10";
const sc_lv<3> awgn_top::ap_ST_fsm_state3 = "100";
const sc_lv<32> awgn_top::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> awgn_top::ap_const_lv1_1 = "1";
const sc_lv<32> awgn_top::ap_const_lv32_2 = "10";
const sc_lv<32> awgn_top::ap_const_lv32_1 = "1";

awgn_top::awgn_top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_operator_s_fu_49 = new operator_s("grp_operator_s_fu_49");
    grp_operator_s_fu_49->ap_clk(ap_clk);
    grp_operator_s_fu_49->ap_rst(ap_rst);
    grp_operator_s_fu_49->ap_start(grp_operator_s_fu_49_ap_start);
    grp_operator_s_fu_49->ap_done(grp_operator_s_fu_49_ap_done);
    grp_operator_s_fu_49->ap_idle(grp_operator_s_fu_49_ap_idle);
    grp_operator_s_fu_49->ap_ready(grp_operator_s_fu_49_ap_ready);
    grp_operator_s_fu_49->snr_V_read(tmp_V_1_reg_63);
    grp_operator_s_fu_49->ap_return(grp_operator_s_fu_49_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( noise_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( noise_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_grp_operator_s_fu_49_ap_start);
    sensitive << ( ap_reg_grp_operator_s_fu_49_ap_start );

    SC_METHOD(thread_noise_V_V_blk_n);
    sensitive << ( noise_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_noise_V_V_din);
    sensitive << ( noise_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( noiseSample_V_reg_68 );

    SC_METHOD(thread_noise_V_V_write);
    sensitive << ( noise_V_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_snr_V_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( snr_V_V_empty_n );

    SC_METHOD(thread_snr_V_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( snr_V_V_empty_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( snr_V_V_empty_n );
    sensitive << ( noise_V_V_full_n );
    sensitive << ( grp_operator_s_fu_49_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    ap_reg_grp_operator_s_fu_49_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "awgn_top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, snr_V_V_dout, "(port)snr_V_V_dout");
    sc_trace(mVcdFile, snr_V_V_empty_n, "(port)snr_V_V_empty_n");
    sc_trace(mVcdFile, snr_V_V_read, "(port)snr_V_V_read");
    sc_trace(mVcdFile, noise_V_V_din, "(port)noise_V_V_din");
    sc_trace(mVcdFile, noise_V_V_full_n, "(port)noise_V_V_full_n");
    sc_trace(mVcdFile, noise_V_V_write, "(port)noise_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, snr_V_V_blk_n, "snr_V_V_blk_n");
    sc_trace(mVcdFile, noise_V_V_blk_n, "noise_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_V_1_reg_63, "tmp_V_1_reg_63");
    sc_trace(mVcdFile, grp_operator_s_fu_49_ap_return, "grp_operator_s_fu_49_ap_return");
    sc_trace(mVcdFile, noiseSample_V_reg_68, "noiseSample_V_reg_68");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_operator_s_fu_49_ap_done, "grp_operator_s_fu_49_ap_done");
    sc_trace(mVcdFile, grp_operator_s_fu_49_ap_start, "grp_operator_s_fu_49_ap_start");
    sc_trace(mVcdFile, grp_operator_s_fu_49_ap_idle, "grp_operator_s_fu_49_ap_idle");
    sc_trace(mVcdFile, grp_operator_s_fu_49_ap_ready, "grp_operator_s_fu_49_ap_ready");
    sc_trace(mVcdFile, ap_reg_grp_operator_s_fu_49_ap_start, "ap_reg_grp_operator_s_fu_49_ap_start");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("awgn_top.hdltvin.dat");
    mHdltvoutHandle.open("awgn_top.hdltvout.dat");
}

awgn_top::~awgn_top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_operator_s_fu_49;
}

void awgn_top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_operator_s_fu_49_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(snr_V_V_empty_n.read(), ap_const_logic_0)))) {
            ap_reg_grp_operator_s_fu_49_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_operator_s_fu_49_ap_ready.read())) {
            ap_reg_grp_operator_s_fu_49_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_operator_s_fu_49_ap_done.read()))) {
        noiseSample_V_reg_68 = grp_operator_s_fu_49_ap_return.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(snr_V_V_empty_n.read(), ap_const_logic_0)))) {
        tmp_V_1_reg_63 = snr_V_V_dout.read();
    }
}

void awgn_top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void awgn_top::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void awgn_top::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void awgn_top::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(noise_V_V_full_n.read(), ap_const_logic_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void awgn_top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void awgn_top::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(noise_V_V_full_n.read(), ap_const_logic_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void awgn_top::thread_grp_operator_s_fu_49_ap_start() {
    grp_operator_s_fu_49_ap_start = ap_reg_grp_operator_s_fu_49_ap_start.read();
}

void awgn_top::thread_noise_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        noise_V_V_blk_n = noise_V_V_full_n.read();
    } else {
        noise_V_V_blk_n = ap_const_logic_1;
    }
}

void awgn_top::thread_noise_V_V_din() {
    noise_V_V_din = noiseSample_V_reg_68.read();
}

void awgn_top::thread_noise_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         !esl_seteq<1,1,1>(noise_V_V_full_n.read(), ap_const_logic_0))) {
        noise_V_V_write = ap_const_logic_1;
    } else {
        noise_V_V_write = ap_const_logic_0;
    }
}

void awgn_top::thread_snr_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        snr_V_V_blk_n = snr_V_V_empty_n.read();
    } else {
        snr_V_V_blk_n = ap_const_logic_1;
    }
}

void awgn_top::thread_snr_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(snr_V_V_empty_n.read(), ap_const_logic_0)))) {
        snr_V_V_read = ap_const_logic_1;
    } else {
        snr_V_V_read = ap_const_logic_0;
    }
}

void awgn_top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(snr_V_V_empty_n.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_operator_s_fu_49_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(noise_V_V_full_n.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void awgn_top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"snr_V_V_dout\" :  \"" << snr_V_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"snr_V_V_empty_n\" :  \"" << snr_V_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"snr_V_V_read\" :  \"" << snr_V_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"noise_V_V_din\" :  \"" << noise_V_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"noise_V_V_full_n\" :  \"" << noise_V_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"noise_V_V_write\" :  \"" << noise_V_V_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

