// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "operator_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic operator_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic operator_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> operator_s::ap_ST_fsm_state1 = "1";
const sc_lv<9> operator_s::ap_ST_fsm_state2 = "10";
const sc_lv<9> operator_s::ap_ST_fsm_state3 = "100";
const sc_lv<9> operator_s::ap_ST_fsm_state4 = "1000";
const sc_lv<9> operator_s::ap_ST_fsm_state5 = "10000";
const sc_lv<9> operator_s::ap_ST_fsm_state6 = "100000";
const sc_lv<9> operator_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> operator_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> operator_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> operator_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> operator_s::ap_const_lv1_1 = "1";
const sc_lv<32> operator_s::ap_const_lv32_1 = "1";
const sc_lv<1> operator_s::ap_const_lv1_0 = "0";
const sc_lv<32> operator_s::ap_const_lv32_2 = "10";
const sc_lv<32> operator_s::ap_const_lv32_4 = "100";
const sc_lv<32> operator_s::ap_const_lv32_5 = "101";
const sc_lv<32> operator_s::ap_const_lv32_6 = "110";
const sc_lv<32> operator_s::ap_const_lv32_7 = "111";
const sc_lv<3> operator_s::ap_const_lv3_0 = "000";
const sc_lv<32> operator_s::ap_const_lv32_3 = "11";
const sc_lv<2> operator_s::ap_const_lv2_0 = "00";
const sc_lv<3> operator_s::ap_const_lv3_4 = "100";
const sc_lv<3> operator_s::ap_const_lv3_1 = "1";
const sc_lv<5> operator_s::ap_const_lv5_0 = "00000";
const sc_lv<32> operator_s::ap_const_lv32_1F = "11111";
const sc_lv<32> operator_s::ap_const_lv32_F = "1111";
const sc_lv<32> operator_s::ap_const_lv32_1D = "11101";
const sc_lv<2> operator_s::ap_const_lv2_2 = "10";
const sc_lv<2> operator_s::ap_const_lv2_1 = "1";
const sc_lv<9> operator_s::ap_const_lv9_0 = "000000000";
const sc_lv<32> operator_s::ap_const_lv32_40 = "1000000";
const sc_lv<32> operator_s::ap_const_lv32_7F = "1111111";
const sc_lv<32> operator_s::ap_const_lv32_5D = "1011101";
const sc_lv<34> operator_s::ap_const_lv34_0 = "0000000000000000000000000000000000";
const sc_lv<32> operator_s::ap_const_lv32_23 = "100011";
const sc_lv<32> operator_s::ap_const_lv32_3F = "111111";
const sc_lv<64> operator_s::ap_const_lv64_1 = "1";
const sc_lv<58> operator_s::ap_const_lv58_0 = "0000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> operator_s::ap_const_lv32_D = "1101";
const sc_lv<64> operator_s::ap_const_lv64_7 = "111";
const sc_lv<32> operator_s::ap_const_lv32_A = "1010";
const sc_lv<32> operator_s::ap_const_lv32_E = "1110";
const sc_lv<3> operator_s::ap_const_lv3_3 = "11";
const sc_lv<4> operator_s::ap_const_lv4_1 = "1";
const sc_lv<4> operator_s::ap_const_lv4_F = "1111";
const sc_lv<4> operator_s::ap_const_lv4_8 = "1000";
const sc_lv<9> operator_s::ap_const_lv9_1 = "1";
const sc_lv<10> operator_s::ap_const_lv10_0 = "0000000000";
const sc_lv<32> operator_s::ap_const_lv32_8 = "1000";
const sc_lv<49> operator_s::ap_const_lv49_10000000 = "10000000000000000000000000000";
const sc_lv<32> operator_s::ap_const_lv32_2F = "101111";
const sc_lv<32> operator_s::ap_const_lv32_2C = "101100";
const sc_lv<4> operator_s::ap_const_lv4_0 = "0000";
const sc_lv<19> operator_s::ap_const_lv19_78001 = "1111000000000000001";
const sc_lv<16> operator_s::ap_const_lv16_7FFF = "111111111111111";
const sc_lv<16> operator_s::ap_const_lv16_8001 = "1000000000000001";

operator_s::operator_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    coarseContents_U = new operator_s_coarsebkb("coarseContents_U");
    coarseContents_U->clk(ap_clk);
    coarseContents_U->reset(ap_rst);
    coarseContents_U->address0(coarseContents_address0);
    coarseContents_U->ce0(coarseContents_ce0);
    coarseContents_U->q0(coarseContents_q0);
    gradientContents_U = new operator_s_gradiecud("gradientContents_U");
    gradientContents_U->clk(ap_clk);
    gradientContents_U->reset(ap_rst);
    gradientContents_U->address0(gradientContents_address0);
    gradientContents_U->ce0(gradientContents_ce0);
    gradientContents_U->q0(gradientContents_q0);
    scaleLookup_U = new operator_s_scaleLdEe("scaleLookup_U");
    scaleLookup_U->clk(ap_clk);
    scaleLookup_U->reset(ap_rst);
    scaleLookup_U->address0(scaleLookup_address0);
    scaleLookup_U->ce0(scaleLookup_ce0);
    scaleLookup_U->q0(scaleLookup_q0);
    norm_V_U = new operator_s_norm_V("norm_V_U");
    norm_V_U->clk(ap_clk);
    norm_V_U->reset(ap_rst);
    norm_V_U->address0(norm_V_address0);
    norm_V_U->ce0(norm_V_ce0);
    norm_V_U->we0(norm_V_we0);
    norm_V_U->d0(norm_V_d0);
    norm_V_U->q0(norm_V_q0);
    awgn_top_mux_42_9_1_U0 = new awgn_top_mux_42_9_1<1,1,9,9,9,9,2,9>("awgn_top_mux_42_9_1_U0");
    awgn_top_mux_42_9_1_U0->din1(bramChapter_3_V_1_fu_140);
    awgn_top_mux_42_9_1_U0->din2(bramChapter_3_V_2_fu_144);
    awgn_top_mux_42_9_1_U0->din3(bramChapter_3_V_4_fu_148);
    awgn_top_mux_42_9_1_U0->din4(bramChapter_3_V_fu_152);
    awgn_top_mux_42_9_1_U0->din5(tmp_21_reg_1302);
    awgn_top_mux_42_9_1_U0->dout(grp_fu_318_p6);
    awgn_top_mul_mul_eOg_U1 = new awgn_top_mul_mul_eOg<1,1,13,10,23>("awgn_top_mul_mul_eOg_U1");
    awgn_top_mul_mul_eOg_U1->din0(r_V_12_fu_1239_p0);
    awgn_top_mul_mul_eOg_U1->din1(tmp_23_reg_1382);
    awgn_top_mul_mul_eOg_U1->dout(r_V_12_fu_1239_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_6_fu_1225_p2 );
    sensitive << ( saturatedNoise_V_1_fu_1217_p3 );
    sensitive << ( saturatedNoise_V_fu_1207_p4 );

    SC_METHOD(thread_bramChapter_0_V_1_fu_486_p3);
    sensitive << ( sel_tmp2_fu_426_p2 );
    sensitive << ( bramChapter_3_V_1_fu_140 );

    SC_METHOD(thread_bramChapter_1_V_1_fu_478_p3);
    sensitive << ( sel_tmp2_fu_426_p2 );
    sensitive << ( bramChapter_3_V_2_fu_144 );
    sensitive << ( sel_tmp3_fu_470_p3 );

    SC_METHOD(thread_bramChapter_3_V_10_fu_763_p2);
    sensitive << ( grp_fu_318_p6 );
    sensitive << ( r_V_16_fu_757_p2 );

    SC_METHOD(thread_bramChapter_3_V_3_fu_776_p3);
    sensitive << ( or_cond_reg_1351 );
    sensitive << ( bramChapter_3_V_fu_152 );
    sensitive << ( newSel15_fu_769_p3 );

    SC_METHOD(thread_bramChapter_3_V_5_fu_790_p3);
    sensitive << ( or_cond_reg_1351 );
    sensitive << ( bramChapter_3_V_4_fu_148 );
    sensitive << ( newSel16_fu_783_p3 );

    SC_METHOD(thread_bramChapter_3_V_7_fu_797_p3);
    sensitive << ( sel_tmp1_reg_1333 );
    sensitive << ( bramChapter_3_V_2_fu_144 );
    sensitive << ( bramChapter_3_V_10_fu_763_p2 );

    SC_METHOD(thread_bramChapter_3_V_8_fu_804_p3);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( bramChapter_3_V_2_fu_144 );
    sensitive << ( bramChapter_3_V_7_fu_797_p3 );

    SC_METHOD(thread_bramChapter_3_V_9_fu_811_p3);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( bramChapter_3_V_1_fu_140 );
    sensitive << ( bramChapter_3_V_10_fu_763_p2 );

    SC_METHOD(thread_centralLimitNoise_V_fu_1148_p2);
    sensitive << ( tmp184_cast_fu_1144_p1 );
    sensitive << ( tmp183_cast_fu_1134_p1 );

    SC_METHOD(thread_coarseContents_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_13_fu_700_p1 );

    SC_METHOD(thread_coarseContents_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_exitcond1_fu_362_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_283 );

    SC_METHOD(thread_exitcond_fu_666_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( normStage_reg_294 );

    SC_METHOD(thread_gradientContents_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_13_fu_700_p1 );

    SC_METHOD(thread_gradientContents_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_i_1_fu_368_p2);
    sensitive << ( i_reg_283 );

    SC_METHOD(thread_i_cast_cast_fu_335_p1);
    sensitive << ( i_reg_283 );

    SC_METHOD(thread_icmp_fu_1195_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_20_fu_1185_p4 );

    SC_METHOD(thread_lfsr1_V_fu_514_p4);
    sensitive << ( p_Val2_s_reg_1278 );

    SC_METHOD(thread_lfsr2_V_fu_523_p1);
    sensitive << ( p_Val2_s_reg_1278 );

    SC_METHOD(thread_newSel10_fu_1042_p3);
    sensitive << ( noiseGen_V_2_reg_247 );
    sensitive << ( or_cond3_fu_985_p2 );
    sensitive << ( newSel9_fu_1027_p3 );

    SC_METHOD(thread_newSel11_fu_1058_p3);
    sensitive << ( noiseGen_3_V_2_reg_259 );
    sensitive << ( sel_tmp12_fu_959_p2 );
    sensitive << ( noiseGen_0_V_fu_928_p2 );

    SC_METHOD(thread_newSel12_fu_1066_p3);
    sensitive << ( sel_tmp10_reg_1410 );
    sensitive << ( noiseGen_3_V_2_reg_259 );
    sensitive << ( noiseGen_0_V_2_fu_934_p2 );

    SC_METHOD(thread_newSel13_fu_1073_p3);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( noiseGen_3_V_2_reg_259 );
    sensitive << ( newSel11_fu_1058_p3 );

    SC_METHOD(thread_newSel14_fu_1080_p3);
    sensitive << ( noiseGen_3_V_2_reg_259 );
    sensitive << ( or_cond3_fu_985_p2 );
    sensitive << ( newSel12_fu_1066_p3 );

    SC_METHOD(thread_newSel15_fu_769_p3);
    sensitive << ( sel_tmp_reg_1325 );
    sensitive << ( bramChapter_3_V_fu_152 );
    sensitive << ( bramChapter_3_V_10_fu_763_p2 );

    SC_METHOD(thread_newSel16_fu_783_p3);
    sensitive << ( sel_tmp_reg_1325 );
    sensitive << ( bramChapter_3_V_4_fu_148 );
    sensitive << ( bramChapter_3_V_10_fu_763_p2 );

    SC_METHOD(thread_newSel1_fu_446_p3);
    sensitive << ( or_cond_fu_432_p2 );
    sensitive << ( bramChapter_3_V_fu_152 );
    sensitive << ( newSel_fu_438_p3 );

    SC_METHOD(thread_newSel2_fu_454_p3);
    sensitive << ( sel_tmp_fu_414_p2 );
    sensitive << ( bramChapter_3_V_4_fu_148 );

    SC_METHOD(thread_newSel3_fu_462_p3);
    sensitive << ( or_cond_fu_432_p2 );
    sensitive << ( bramChapter_3_V_4_fu_148 );
    sensitive << ( newSel2_fu_454_p3 );

    SC_METHOD(thread_newSel4_fu_978_p3);
    sensitive << ( sel_tmp10_reg_1410 );
    sensitive << ( noiseGen_V_3_reg_235 );
    sensitive << ( noiseGen_0_V_fu_928_p2 );

    SC_METHOD(thread_newSel5_fu_990_p3);
    sensitive << ( noiseGen_V_3_reg_235 );
    sensitive << ( sel_tmp5_fu_945_p2 );
    sensitive << ( noiseGen_0_V_2_fu_934_p2 );

    SC_METHOD(thread_newSel6_fu_1003_p3);
    sensitive << ( or_cond3_fu_985_p2 );
    sensitive << ( newSel4_fu_978_p3 );
    sensitive << ( newSel5_fu_990_p3 );

    SC_METHOD(thread_newSel7_fu_1035_p3);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( noiseGen_V_2_reg_247 );
    sensitive << ( newSel8_fu_1019_p3 );

    SC_METHOD(thread_newSel8_fu_1019_p3);
    sensitive << ( noiseGen_V_2_reg_247 );
    sensitive << ( sel_tmp12_fu_959_p2 );
    sensitive << ( noiseGen_0_V_fu_928_p2 );

    SC_METHOD(thread_newSel9_fu_1027_p3);
    sensitive << ( noiseGen_V_2_reg_247 );
    sensitive << ( sel_tmp5_fu_945_p2 );
    sensitive << ( noiseGen_0_V_2_fu_934_p2 );

    SC_METHOD(thread_newSel_fu_438_p3);
    sensitive << ( sel_tmp_fu_414_p2 );
    sensitive << ( bramChapter_3_V_fu_152 );

    SC_METHOD(thread_noiseGen_0_V_2_fu_934_p2);
    sensitive << ( tmp_14_fu_914_p1 );
    sensitive << ( r_V_11_cast_fu_924_p1 );

    SC_METHOD(thread_noiseGen_0_V_fu_928_p2);
    sensitive << ( tmp_14_fu_914_p1 );
    sensitive << ( r_V_11_cast_fu_924_p1 );

    SC_METHOD(thread_noiseGen_3_V_1_fu_1050_p3);
    sensitive << ( or_cond4_fu_998_p2 );
    sensitive << ( newSel7_fu_1035_p3 );
    sensitive << ( newSel10_fu_1042_p3 );

    SC_METHOD(thread_noiseGen_3_V_3_fu_1088_p3);
    sensitive << ( or_cond4_fu_998_p2 );
    sensitive << ( newSel13_fu_1073_p3 );
    sensitive << ( newSel14_fu_1080_p3 );

    SC_METHOD(thread_noiseGen_3_V_5_fu_1096_p3);
    sensitive << ( noiseGen_3_V_4_reg_271 );
    sensitive << ( noiseGen_0_V_2_fu_934_p2 );
    sensitive << ( sel_tmp13_fu_963_p2 );

    SC_METHOD(thread_noiseGen_3_V_6_fu_1104_p3);
    sensitive << ( noiseGen_0_V_fu_928_p2 );
    sensitive << ( sel_tmp14_fu_968_p2 );
    sensitive << ( noiseGen_3_V_5_fu_1096_p3 );

    SC_METHOD(thread_noiseGen_3_V_fu_1011_p3);
    sensitive << ( noiseGen_V_3_reg_235 );
    sensitive << ( or_cond4_fu_998_p2 );
    sensitive << ( newSel6_fu_1003_p3 );

    SC_METHOD(thread_normStage_1_fu_672_p2);
    sensitive << ( normStage_reg_294 );

    SC_METHOD(thread_normStage_cast1_cast_fu_648_p1);
    sensitive << ( normStage_reg_294 );

    SC_METHOD(thread_normStage_cast_fu_662_p1);
    sensitive << ( normStage_reg_294 );

    SC_METHOD(thread_norm_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_cast_fu_357_p1 );
    sensitive << ( tmp_26_cast_fu_657_p1 );
    sensitive << ( tmp_28_cast_fu_826_p1 );
    sensitive << ( phitmp4_fu_742_p2 );
    sensitive << ( tmp_27_cast_fu_859_p1 );

    SC_METHOD(thread_norm_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( phitmp4_fu_742_p2 );

    SC_METHOD(thread_norm_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_V_9_fu_390_p2 );
    sensitive << ( norm_V_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( phitmp4_fu_742_p2 );
    sensitive << ( r_V_15_fu_868_p2 );

    SC_METHOD(thread_norm_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_362_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( phitmp4_fu_742_p2 );

    SC_METHOD(thread_op2_assign_1_cast_fu_728_p1);
    sensitive << ( op2_assign_1_fu_722_p2 );

    SC_METHOD(thread_op2_assign_1_fu_722_p2);
    sensitive << ( r_V_14_fu_716_p2 );

    SC_METHOD(thread_op2_assign_2_cast_fu_712_p1);
    sensitive << ( op2_assign_2_fu_706_p2 );

    SC_METHOD(thread_op2_assign_2_fu_706_p2);
    sensitive << ( normStage_reg_294 );

    SC_METHOD(thread_op2_assign_3_cast_fu_753_p1);
    sensitive << ( op2_assign_3_fu_748_p2 );

    SC_METHOD(thread_op2_assign_3_fu_748_p2);
    sensitive << ( normStage_cast_reg_1367 );

    SC_METHOD(thread_op2_assign_fu_378_p3);
    sensitive << ( tmp_21_fu_374_p1 );

    SC_METHOD(thread_or_cond2_fu_972_p2);
    sensitive << ( sel_tmp12_fu_959_p2 );
    sensitive << ( sel_tmp11_fu_955_p2 );

    SC_METHOD(thread_or_cond3_fu_985_p2);
    sensitive << ( sel_tmp10_reg_1410 );
    sensitive << ( sel_tmp6_fu_950_p2 );

    SC_METHOD(thread_or_cond4_fu_998_p2);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( or_cond2_fu_972_p2 );

    SC_METHOD(thread_or_cond_fu_432_p2);
    sensitive << ( sel_tmp1_fu_420_p2 );
    sensitive << ( sel_tmp2_fu_426_p2 );

    SC_METHOD(thread_p_2_cast_fu_1112_p1);
    sensitive << ( noiseGen_3_V_4_reg_271 );

    SC_METHOD(thread_p_3_cast_fu_1116_p1);
    sensitive << ( noiseGen_3_V_2_reg_259 );

    SC_METHOD(thread_p_Result_s_fu_630_p3);
    sensitive << ( r_V_24_fu_575_p2 );
    sensitive << ( r_V_30_fu_624_p2 );

    SC_METHOD(thread_p_shl_cast_fu_347_p1);
    sensitive << ( tmp_3_fu_339_p3 );

    SC_METHOD(thread_phitmp2_fu_678_p4);
    sensitive << ( r_V_9_reg_1310 );

    SC_METHOD(thread_phitmp4_fu_742_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_24_fu_738_p1 );

    SC_METHOD(thread_r_V_11_cast_fu_924_p1);
    sensitive << ( r_V_13_fu_917_p3 );

    SC_METHOD(thread_r_V_12_fu_1239_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( r_V_12_fu_1239_p00 );

    SC_METHOD(thread_r_V_12_fu_1239_p00);
    sensitive << ( gradientContents_q0 );

    SC_METHOD(thread_r_V_13_fu_917_p3);
    sensitive << ( coarseContents_load_reg_1400 );

    SC_METHOD(thread_r_V_14_fu_716_p2);
    sensitive << ( op2_assign_2_cast_fu_712_p1 );

    SC_METHOD(thread_r_V_15_fu_868_p2);
    sensitive << ( norm_V_q0 );
    sensitive << ( tmp_39_cast_fu_864_p1 );

    SC_METHOD(thread_r_V_16_fu_757_p2);
    sensitive << ( op2_assign_3_cast_fu_753_p1 );

    SC_METHOD(thread_r_V_19_fu_535_p3);
    sensitive << ( tmp_9_fu_526_p4 );

    SC_METHOD(thread_r_V_20_fu_543_p2);
    sensitive << ( r_V_19_fu_535_p3 );
    sensitive << ( lfsr1_V_fu_514_p4 );

    SC_METHOD(thread_r_V_21_fu_559_p1);
    sensitive << ( r_V_s_fu_549_p4 );

    SC_METHOD(thread_r_V_22_fu_563_p2);
    sensitive << ( r_V_20_fu_543_p2 );
    sensitive << ( r_V_21_fu_559_p1 );

    SC_METHOD(thread_r_V_23_fu_569_p2);
    sensitive << ( r_V_22_fu_563_p2 );

    SC_METHOD(thread_r_V_24_fu_575_p2);
    sensitive << ( r_V_22_fu_563_p2 );
    sensitive << ( r_V_23_fu_569_p2 );

    SC_METHOD(thread_r_V_25_fu_584_p3);
    sensitive << ( tmp_18_fu_581_p1 );

    SC_METHOD(thread_r_V_26_fu_592_p2);
    sensitive << ( r_V_25_fu_584_p3 );
    sensitive << ( lfsr2_V_fu_523_p1 );

    SC_METHOD(thread_r_V_27_fu_608_p1);
    sensitive << ( r_V_6_fu_598_p4 );

    SC_METHOD(thread_r_V_28_fu_612_p2);
    sensitive << ( r_V_26_fu_592_p2 );
    sensitive << ( r_V_27_fu_608_p1 );

    SC_METHOD(thread_r_V_29_fu_618_p2);
    sensitive << ( r_V_28_fu_612_p2 );

    SC_METHOD(thread_r_V_30_fu_624_p2);
    sensitive << ( r_V_28_fu_612_p2 );
    sensitive << ( r_V_29_fu_618_p2 );

    SC_METHOD(thread_r_V_31_fu_1160_p0);
    sensitive << ( centralLimitNoise_V_reg_1437 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_r_V_31_fu_1160_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( r_V_31_fu_1160_p10 );

    SC_METHOD(thread_r_V_31_fu_1160_p10);
    sensitive << ( scale_V_reg_1442 );

    SC_METHOD(thread_r_V_31_fu_1160_p2);
    sensitive << ( r_V_31_fu_1160_p0 );
    sensitive << ( r_V_31_fu_1160_p1 );

    SC_METHOD(thread_r_V_6_fu_598_p4);
    sensitive << ( r_V_26_fu_592_p2 );

    SC_METHOD(thread_r_V_9_fu_390_p2);
    sensitive << ( p_Val2_s_reg_1278 );
    sensitive << ( tmp_7_fu_386_p1 );

    SC_METHOD(thread_r_V_fu_1169_p2);
    sensitive << ( tmp_2_fu_1166_p1 );

    SC_METHOD(thread_r_V_s_fu_549_p4);
    sensitive << ( r_V_20_fu_543_p2 );

    SC_METHOD(thread_roundedNoise_V_fu_1175_p4);
    sensitive << ( r_V_fu_1169_p2 );

    SC_METHOD(thread_saturatedNoise_V_1_fu_1217_p3);
    sensitive << ( icmp_fu_1195_p2 );

    SC_METHOD(thread_saturatedNoise_V_fu_1207_p4);
    sensitive << ( r_V_fu_1169_p2 );

    SC_METHOD(thread_scaleLookup_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_s_fu_644_p1 );

    SC_METHOD(thread_scaleLookup_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sel_tmp10_fu_908_p2);
    sensitive << ( tmp13_fu_903_p2 );
    sensitive << ( tmp12_fu_897_p2 );

    SC_METHOD(thread_sel_tmp11_fu_955_p2);
    sensitive << ( tmp_22_reg_1316 );
    sensitive << ( sel_tmp_reg_1325 );

    SC_METHOD(thread_sel_tmp12_fu_959_p2);
    sensitive << ( tmp_22_reg_1316 );
    sensitive << ( sel_tmp1_reg_1333 );

    SC_METHOD(thread_sel_tmp13_fu_963_p2);
    sensitive << ( sel_tmp2_reg_1340 );
    sensitive << ( sel_tmp4_fu_940_p2 );

    SC_METHOD(thread_sel_tmp14_fu_968_p2);
    sensitive << ( tmp_22_reg_1316 );
    sensitive << ( sel_tmp2_reg_1340 );

    SC_METHOD(thread_sel_tmp1_fu_420_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_374_p1 );
    sensitive << ( exitcond1_fu_362_p2 );

    SC_METHOD(thread_sel_tmp2_fu_426_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_374_p1 );
    sensitive << ( exitcond1_fu_362_p2 );

    SC_METHOD(thread_sel_tmp3_fu_470_p3);
    sensitive << ( sel_tmp1_fu_420_p2 );
    sensitive << ( bramChapter_3_V_2_fu_144 );

    SC_METHOD(thread_sel_tmp4_fu_940_p2);
    sensitive << ( tmp_22_reg_1316 );

    SC_METHOD(thread_sel_tmp5_fu_945_p2);
    sensitive << ( sel_tmp_reg_1325 );
    sensitive << ( sel_tmp4_fu_940_p2 );

    SC_METHOD(thread_sel_tmp6_fu_950_p2);
    sensitive << ( sel_tmp1_reg_1333 );
    sensitive << ( sel_tmp4_fu_940_p2 );

    SC_METHOD(thread_sel_tmp7_fu_882_p2);
    sensitive << ( tmp_21_reg_1302 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_sel_tmp8_fu_887_p2);
    sensitive << ( tmp_21_reg_1302 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_sel_tmp9_fu_892_p2);
    sensitive << ( tmp_21_reg_1302 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_sel_tmp_fu_414_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_21_fu_374_p1 );
    sensitive << ( exitcond1_fu_362_p2 );

    SC_METHOD(thread_tmp12_fu_897_p2);
    sensitive << ( sel_tmp7_fu_882_p2 );
    sensitive << ( sel_tmp8_fu_887_p2 );

    SC_METHOD(thread_tmp13_fu_903_p2);
    sensitive << ( tmp_22_reg_1316 );
    sensitive << ( sel_tmp9_fu_892_p2 );

    SC_METHOD(thread_tmp183_cast_fu_1134_p1);
    sensitive << ( tmp_fu_1128_p2 );

    SC_METHOD(thread_tmp184_cast_fu_1144_p1);
    sensitive << ( tmp1_fu_1138_p2 );

    SC_METHOD(thread_tmp1_fu_1138_p2);
    sensitive << ( tmp_cast_fu_1120_p1 );
    sensitive << ( tmp_cast_14_fu_1124_p1 );

    SC_METHOD(thread_tmp_11_fu_687_p1);
    sensitive << ( phitmp2_fu_678_p4 );

    SC_METHOD(thread_tmp_12_fu_691_p2);
    sensitive << ( grp_fu_318_p6 );
    sensitive << ( tmp_11_fu_687_p1 );

    SC_METHOD(thread_tmp_13_fu_700_p1);
    sensitive << ( tmp_12_fu_691_p2 );

    SC_METHOD(thread_tmp_14_fu_914_p1);
    sensitive << ( r_V_12_reg_1405 );

    SC_METHOD(thread_tmp_15_fu_732_p2);
    sensitive << ( norm_V_q0 );
    sensitive << ( op2_assign_1_cast_fu_728_p1 );

    SC_METHOD(thread_tmp_16_fu_854_p2);
    sensitive << ( tmp_8_reg_1287 );
    sensitive << ( tmp_38_cast_cast_fu_851_p1 );

    SC_METHOD(thread_tmp_18_fu_581_p1);
    sensitive << ( p_Val2_s_reg_1278 );

    SC_METHOD(thread_tmp_19_fu_821_p2);
    sensitive << ( tmp_8_reg_1287 );
    sensitive << ( tmp_42_cast_cast_fu_818_p1 );

    SC_METHOD(thread_tmp_20_fu_1185_p4);
    sensitive << ( r_V_fu_1169_p2 );

    SC_METHOD(thread_tmp_21_fu_374_p1);
    sensitive << ( i_reg_283 );

    SC_METHOD(thread_tmp_23_fu_697_p1);
    sensitive << ( r_V_9_reg_1310 );

    SC_METHOD(thread_tmp_24_fu_738_p1);
    sensitive << ( tmp_15_fu_732_p2 );

    SC_METHOD(thread_tmp_26_cast_fu_657_p1);
    sensitive << ( tmp_4_fu_652_p2 );

    SC_METHOD(thread_tmp_27_cast_fu_859_p1);
    sensitive << ( tmp_16_fu_854_p2 );

    SC_METHOD(thread_tmp_28_cast_fu_826_p1);
    sensitive << ( tmp_19_fu_821_p2 );

    SC_METHOD(thread_tmp_2_fu_1166_p1);
    sensitive << ( r_V_31_reg_1447 );

    SC_METHOD(thread_tmp_38_cast_cast_fu_851_p1);
    sensitive << ( normStage_1_reg_1375 );

    SC_METHOD(thread_tmp_39_cast_fu_864_p1);
    sensitive << ( r_V_14_fu_716_p2 );

    SC_METHOD(thread_tmp_3_fu_339_p3);
    sensitive << ( i_reg_283 );

    SC_METHOD(thread_tmp_42_cast_cast_fu_818_p1);
    sensitive << ( normStage_1_reg_1375 );

    SC_METHOD(thread_tmp_4_fu_652_p2);
    sensitive << ( tmp_8_reg_1287 );
    sensitive << ( normStage_cast1_cast_fu_648_p1 );

    SC_METHOD(thread_tmp_5_fu_1201_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( roundedNoise_V_fu_1175_p4 );

    SC_METHOD(thread_tmp_6_fu_1225_p2);
    sensitive << ( icmp_fu_1195_p2 );
    sensitive << ( tmp_5_fu_1201_p2 );

    SC_METHOD(thread_tmp_7_fu_386_p1);
    sensitive << ( op2_assign_fu_378_p3 );

    SC_METHOD(thread_tmp_8_cast_fu_357_p1);
    sensitive << ( tmp_8_fu_351_p2 );

    SC_METHOD(thread_tmp_8_fu_351_p2);
    sensitive << ( i_cast_cast_fu_335_p1 );
    sensitive << ( p_shl_cast_fu_347_p1 );

    SC_METHOD(thread_tmp_9_fu_526_p4);
    sensitive << ( p_Val2_s_reg_1278 );

    SC_METHOD(thread_tmp_cast_14_fu_1124_p1);
    sensitive << ( noiseGen_V_3_reg_235 );

    SC_METHOD(thread_tmp_cast_fu_1120_p1);
    sensitive << ( noiseGen_V_2_reg_247 );

    SC_METHOD(thread_tmp_fu_1128_p2);
    sensitive << ( p_3_cast_fu_1116_p1 );
    sensitive << ( p_2_cast_fu_1112_p1 );

    SC_METHOD(thread_tmp_s_fu_644_p1);
    sensitive << ( snr_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_362_p2 );
    sensitive << ( exitcond_fu_666_p2 );

    ap_CS_fsm = "000000001";
    uut_lfsr128_V = "00000001001000110100010101100111100010011010101111001101111011110001001000110100010101100111100010011010101111001101111011110000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "operator_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, snr_V_read, "(port)snr_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, uut_lfsr128_V, "uut_lfsr128_V");
    sc_trace(mVcdFile, coarseContents_address0, "coarseContents_address0");
    sc_trace(mVcdFile, coarseContents_ce0, "coarseContents_ce0");
    sc_trace(mVcdFile, coarseContents_q0, "coarseContents_q0");
    sc_trace(mVcdFile, gradientContents_address0, "gradientContents_address0");
    sc_trace(mVcdFile, gradientContents_ce0, "gradientContents_ce0");
    sc_trace(mVcdFile, gradientContents_q0, "gradientContents_q0");
    sc_trace(mVcdFile, scaleLookup_address0, "scaleLookup_address0");
    sc_trace(mVcdFile, scaleLookup_ce0, "scaleLookup_ce0");
    sc_trace(mVcdFile, scaleLookup_q0, "scaleLookup_q0");
    sc_trace(mVcdFile, p_Val2_s_reg_1278, "p_Val2_s_reg_1278");
    sc_trace(mVcdFile, tmp_8_fu_351_p2, "tmp_8_fu_351_p2");
    sc_trace(mVcdFile, tmp_8_reg_1287, "tmp_8_reg_1287");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_1_fu_368_p2, "i_1_fu_368_p2");
    sc_trace(mVcdFile, i_1_reg_1297, "i_1_reg_1297");
    sc_trace(mVcdFile, tmp_21_fu_374_p1, "tmp_21_fu_374_p1");
    sc_trace(mVcdFile, tmp_21_reg_1302, "tmp_21_reg_1302");
    sc_trace(mVcdFile, exitcond1_fu_362_p2, "exitcond1_fu_362_p2");
    sc_trace(mVcdFile, r_V_9_fu_390_p2, "r_V_9_fu_390_p2");
    sc_trace(mVcdFile, r_V_9_reg_1310, "r_V_9_reg_1310");
    sc_trace(mVcdFile, tmp_22_reg_1316, "tmp_22_reg_1316");
    sc_trace(mVcdFile, sel_tmp_fu_414_p2, "sel_tmp_fu_414_p2");
    sc_trace(mVcdFile, sel_tmp_reg_1325, "sel_tmp_reg_1325");
    sc_trace(mVcdFile, sel_tmp1_fu_420_p2, "sel_tmp1_fu_420_p2");
    sc_trace(mVcdFile, sel_tmp1_reg_1333, "sel_tmp1_reg_1333");
    sc_trace(mVcdFile, sel_tmp2_fu_426_p2, "sel_tmp2_fu_426_p2");
    sc_trace(mVcdFile, sel_tmp2_reg_1340, "sel_tmp2_reg_1340");
    sc_trace(mVcdFile, or_cond_fu_432_p2, "or_cond_fu_432_p2");
    sc_trace(mVcdFile, or_cond_reg_1351, "or_cond_reg_1351");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, normStage_cast_fu_662_p1, "normStage_cast_fu_662_p1");
    sc_trace(mVcdFile, normStage_cast_reg_1367, "normStage_cast_reg_1367");
    sc_trace(mVcdFile, normStage_1_fu_672_p2, "normStage_1_fu_672_p2");
    sc_trace(mVcdFile, normStage_1_reg_1375, "normStage_1_reg_1375");
    sc_trace(mVcdFile, tmp_23_fu_697_p1, "tmp_23_fu_697_p1");
    sc_trace(mVcdFile, tmp_23_reg_1382, "tmp_23_reg_1382");
    sc_trace(mVcdFile, exitcond_fu_666_p2, "exitcond_fu_666_p2");
    sc_trace(mVcdFile, coarseContents_load_reg_1400, "coarseContents_load_reg_1400");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, r_V_12_fu_1239_p2, "r_V_12_fu_1239_p2");
    sc_trace(mVcdFile, r_V_12_reg_1405, "r_V_12_reg_1405");
    sc_trace(mVcdFile, sel_tmp10_fu_908_p2, "sel_tmp10_fu_908_p2");
    sc_trace(mVcdFile, sel_tmp10_reg_1410, "sel_tmp10_reg_1410");
    sc_trace(mVcdFile, noiseGen_3_V_fu_1011_p3, "noiseGen_3_V_fu_1011_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, noiseGen_3_V_1_fu_1050_p3, "noiseGen_3_V_1_fu_1050_p3");
    sc_trace(mVcdFile, noiseGen_3_V_3_fu_1088_p3, "noiseGen_3_V_3_fu_1088_p3");
    sc_trace(mVcdFile, noiseGen_3_V_6_fu_1104_p3, "noiseGen_3_V_6_fu_1104_p3");
    sc_trace(mVcdFile, centralLimitNoise_V_fu_1148_p2, "centralLimitNoise_V_fu_1148_p2");
    sc_trace(mVcdFile, centralLimitNoise_V_reg_1437, "centralLimitNoise_V_reg_1437");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, scale_V_reg_1442, "scale_V_reg_1442");
    sc_trace(mVcdFile, r_V_31_fu_1160_p2, "r_V_31_fu_1160_p2");
    sc_trace(mVcdFile, r_V_31_reg_1447, "r_V_31_reg_1447");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, norm_V_address0, "norm_V_address0");
    sc_trace(mVcdFile, norm_V_ce0, "norm_V_ce0");
    sc_trace(mVcdFile, norm_V_we0, "norm_V_we0");
    sc_trace(mVcdFile, norm_V_d0, "norm_V_d0");
    sc_trace(mVcdFile, norm_V_q0, "norm_V_q0");
    sc_trace(mVcdFile, noiseGen_V_3_reg_235, "noiseGen_V_3_reg_235");
    sc_trace(mVcdFile, noiseGen_V_2_reg_247, "noiseGen_V_2_reg_247");
    sc_trace(mVcdFile, noiseGen_3_V_2_reg_259, "noiseGen_3_V_2_reg_259");
    sc_trace(mVcdFile, noiseGen_3_V_4_reg_271, "noiseGen_3_V_4_reg_271");
    sc_trace(mVcdFile, i_reg_283, "i_reg_283");
    sc_trace(mVcdFile, normStage_reg_294, "normStage_reg_294");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_8_cast_fu_357_p1, "tmp_8_cast_fu_357_p1");
    sc_trace(mVcdFile, tmp_s_fu_644_p1, "tmp_s_fu_644_p1");
    sc_trace(mVcdFile, tmp_26_cast_fu_657_p1, "tmp_26_cast_fu_657_p1");
    sc_trace(mVcdFile, tmp_13_fu_700_p1, "tmp_13_fu_700_p1");
    sc_trace(mVcdFile, tmp_28_cast_fu_826_p1, "tmp_28_cast_fu_826_p1");
    sc_trace(mVcdFile, phitmp4_fu_742_p2, "phitmp4_fu_742_p2");
    sc_trace(mVcdFile, tmp_27_cast_fu_859_p1, "tmp_27_cast_fu_859_p1");
    sc_trace(mVcdFile, p_Result_s_fu_630_p3, "p_Result_s_fu_630_p3");
    sc_trace(mVcdFile, bramChapter_3_V_1_fu_140, "bramChapter_3_V_1_fu_140");
    sc_trace(mVcdFile, bramChapter_0_V_1_fu_486_p3, "bramChapter_0_V_1_fu_486_p3");
    sc_trace(mVcdFile, bramChapter_3_V_9_fu_811_p3, "bramChapter_3_V_9_fu_811_p3");
    sc_trace(mVcdFile, bramChapter_3_V_2_fu_144, "bramChapter_3_V_2_fu_144");
    sc_trace(mVcdFile, bramChapter_1_V_1_fu_478_p3, "bramChapter_1_V_1_fu_478_p3");
    sc_trace(mVcdFile, bramChapter_3_V_8_fu_804_p3, "bramChapter_3_V_8_fu_804_p3");
    sc_trace(mVcdFile, bramChapter_3_V_4_fu_148, "bramChapter_3_V_4_fu_148");
    sc_trace(mVcdFile, newSel3_fu_462_p3, "newSel3_fu_462_p3");
    sc_trace(mVcdFile, bramChapter_3_V_5_fu_790_p3, "bramChapter_3_V_5_fu_790_p3");
    sc_trace(mVcdFile, bramChapter_3_V_fu_152, "bramChapter_3_V_fu_152");
    sc_trace(mVcdFile, newSel1_fu_446_p3, "newSel1_fu_446_p3");
    sc_trace(mVcdFile, bramChapter_3_V_3_fu_776_p3, "bramChapter_3_V_3_fu_776_p3");
    sc_trace(mVcdFile, r_V_15_fu_868_p2, "r_V_15_fu_868_p2");
    sc_trace(mVcdFile, tmp_3_fu_339_p3, "tmp_3_fu_339_p3");
    sc_trace(mVcdFile, i_cast_cast_fu_335_p1, "i_cast_cast_fu_335_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_347_p1, "p_shl_cast_fu_347_p1");
    sc_trace(mVcdFile, op2_assign_fu_378_p3, "op2_assign_fu_378_p3");
    sc_trace(mVcdFile, tmp_7_fu_386_p1, "tmp_7_fu_386_p1");
    sc_trace(mVcdFile, newSel_fu_438_p3, "newSel_fu_438_p3");
    sc_trace(mVcdFile, newSel2_fu_454_p3, "newSel2_fu_454_p3");
    sc_trace(mVcdFile, sel_tmp3_fu_470_p3, "sel_tmp3_fu_470_p3");
    sc_trace(mVcdFile, tmp_9_fu_526_p4, "tmp_9_fu_526_p4");
    sc_trace(mVcdFile, r_V_19_fu_535_p3, "r_V_19_fu_535_p3");
    sc_trace(mVcdFile, lfsr1_V_fu_514_p4, "lfsr1_V_fu_514_p4");
    sc_trace(mVcdFile, r_V_20_fu_543_p2, "r_V_20_fu_543_p2");
    sc_trace(mVcdFile, r_V_s_fu_549_p4, "r_V_s_fu_549_p4");
    sc_trace(mVcdFile, r_V_21_fu_559_p1, "r_V_21_fu_559_p1");
    sc_trace(mVcdFile, r_V_22_fu_563_p2, "r_V_22_fu_563_p2");
    sc_trace(mVcdFile, r_V_23_fu_569_p2, "r_V_23_fu_569_p2");
    sc_trace(mVcdFile, tmp_18_fu_581_p1, "tmp_18_fu_581_p1");
    sc_trace(mVcdFile, r_V_25_fu_584_p3, "r_V_25_fu_584_p3");
    sc_trace(mVcdFile, lfsr2_V_fu_523_p1, "lfsr2_V_fu_523_p1");
    sc_trace(mVcdFile, r_V_26_fu_592_p2, "r_V_26_fu_592_p2");
    sc_trace(mVcdFile, r_V_6_fu_598_p4, "r_V_6_fu_598_p4");
    sc_trace(mVcdFile, r_V_27_fu_608_p1, "r_V_27_fu_608_p1");
    sc_trace(mVcdFile, r_V_28_fu_612_p2, "r_V_28_fu_612_p2");
    sc_trace(mVcdFile, r_V_29_fu_618_p2, "r_V_29_fu_618_p2");
    sc_trace(mVcdFile, r_V_24_fu_575_p2, "r_V_24_fu_575_p2");
    sc_trace(mVcdFile, r_V_30_fu_624_p2, "r_V_30_fu_624_p2");
    sc_trace(mVcdFile, normStage_cast1_cast_fu_648_p1, "normStage_cast1_cast_fu_648_p1");
    sc_trace(mVcdFile, tmp_4_fu_652_p2, "tmp_4_fu_652_p2");
    sc_trace(mVcdFile, phitmp2_fu_678_p4, "phitmp2_fu_678_p4");
    sc_trace(mVcdFile, grp_fu_318_p6, "grp_fu_318_p6");
    sc_trace(mVcdFile, tmp_11_fu_687_p1, "tmp_11_fu_687_p1");
    sc_trace(mVcdFile, tmp_12_fu_691_p2, "tmp_12_fu_691_p2");
    sc_trace(mVcdFile, op2_assign_2_fu_706_p2, "op2_assign_2_fu_706_p2");
    sc_trace(mVcdFile, op2_assign_2_cast_fu_712_p1, "op2_assign_2_cast_fu_712_p1");
    sc_trace(mVcdFile, r_V_14_fu_716_p2, "r_V_14_fu_716_p2");
    sc_trace(mVcdFile, op2_assign_1_fu_722_p2, "op2_assign_1_fu_722_p2");
    sc_trace(mVcdFile, op2_assign_1_cast_fu_728_p1, "op2_assign_1_cast_fu_728_p1");
    sc_trace(mVcdFile, tmp_15_fu_732_p2, "tmp_15_fu_732_p2");
    sc_trace(mVcdFile, tmp_24_fu_738_p1, "tmp_24_fu_738_p1");
    sc_trace(mVcdFile, op2_assign_3_fu_748_p2, "op2_assign_3_fu_748_p2");
    sc_trace(mVcdFile, op2_assign_3_cast_fu_753_p1, "op2_assign_3_cast_fu_753_p1");
    sc_trace(mVcdFile, r_V_16_fu_757_p2, "r_V_16_fu_757_p2");
    sc_trace(mVcdFile, bramChapter_3_V_10_fu_763_p2, "bramChapter_3_V_10_fu_763_p2");
    sc_trace(mVcdFile, newSel15_fu_769_p3, "newSel15_fu_769_p3");
    sc_trace(mVcdFile, newSel16_fu_783_p3, "newSel16_fu_783_p3");
    sc_trace(mVcdFile, bramChapter_3_V_7_fu_797_p3, "bramChapter_3_V_7_fu_797_p3");
    sc_trace(mVcdFile, tmp_42_cast_cast_fu_818_p1, "tmp_42_cast_cast_fu_818_p1");
    sc_trace(mVcdFile, tmp_19_fu_821_p2, "tmp_19_fu_821_p2");
    sc_trace(mVcdFile, tmp_38_cast_cast_fu_851_p1, "tmp_38_cast_cast_fu_851_p1");
    sc_trace(mVcdFile, tmp_16_fu_854_p2, "tmp_16_fu_854_p2");
    sc_trace(mVcdFile, tmp_39_cast_fu_864_p1, "tmp_39_cast_fu_864_p1");
    sc_trace(mVcdFile, sel_tmp7_fu_882_p2, "sel_tmp7_fu_882_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_887_p2, "sel_tmp8_fu_887_p2");
    sc_trace(mVcdFile, sel_tmp9_fu_892_p2, "sel_tmp9_fu_892_p2");
    sc_trace(mVcdFile, tmp13_fu_903_p2, "tmp13_fu_903_p2");
    sc_trace(mVcdFile, tmp12_fu_897_p2, "tmp12_fu_897_p2");
    sc_trace(mVcdFile, r_V_13_fu_917_p3, "r_V_13_fu_917_p3");
    sc_trace(mVcdFile, tmp_14_fu_914_p1, "tmp_14_fu_914_p1");
    sc_trace(mVcdFile, r_V_11_cast_fu_924_p1, "r_V_11_cast_fu_924_p1");
    sc_trace(mVcdFile, sel_tmp4_fu_940_p2, "sel_tmp4_fu_940_p2");
    sc_trace(mVcdFile, sel_tmp12_fu_959_p2, "sel_tmp12_fu_959_p2");
    sc_trace(mVcdFile, sel_tmp11_fu_955_p2, "sel_tmp11_fu_955_p2");
    sc_trace(mVcdFile, noiseGen_0_V_fu_928_p2, "noiseGen_0_V_fu_928_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_950_p2, "sel_tmp6_fu_950_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_945_p2, "sel_tmp5_fu_945_p2");
    sc_trace(mVcdFile, noiseGen_0_V_2_fu_934_p2, "noiseGen_0_V_2_fu_934_p2");
    sc_trace(mVcdFile, or_cond2_fu_972_p2, "or_cond2_fu_972_p2");
    sc_trace(mVcdFile, or_cond3_fu_985_p2, "or_cond3_fu_985_p2");
    sc_trace(mVcdFile, newSel4_fu_978_p3, "newSel4_fu_978_p3");
    sc_trace(mVcdFile, newSel5_fu_990_p3, "newSel5_fu_990_p3");
    sc_trace(mVcdFile, or_cond4_fu_998_p2, "or_cond4_fu_998_p2");
    sc_trace(mVcdFile, newSel6_fu_1003_p3, "newSel6_fu_1003_p3");
    sc_trace(mVcdFile, newSel8_fu_1019_p3, "newSel8_fu_1019_p3");
    sc_trace(mVcdFile, newSel9_fu_1027_p3, "newSel9_fu_1027_p3");
    sc_trace(mVcdFile, newSel7_fu_1035_p3, "newSel7_fu_1035_p3");
    sc_trace(mVcdFile, newSel10_fu_1042_p3, "newSel10_fu_1042_p3");
    sc_trace(mVcdFile, newSel11_fu_1058_p3, "newSel11_fu_1058_p3");
    sc_trace(mVcdFile, newSel12_fu_1066_p3, "newSel12_fu_1066_p3");
    sc_trace(mVcdFile, newSel13_fu_1073_p3, "newSel13_fu_1073_p3");
    sc_trace(mVcdFile, newSel14_fu_1080_p3, "newSel14_fu_1080_p3");
    sc_trace(mVcdFile, sel_tmp13_fu_963_p2, "sel_tmp13_fu_963_p2");
    sc_trace(mVcdFile, sel_tmp14_fu_968_p2, "sel_tmp14_fu_968_p2");
    sc_trace(mVcdFile, noiseGen_3_V_5_fu_1096_p3, "noiseGen_3_V_5_fu_1096_p3");
    sc_trace(mVcdFile, p_3_cast_fu_1116_p1, "p_3_cast_fu_1116_p1");
    sc_trace(mVcdFile, p_2_cast_fu_1112_p1, "p_2_cast_fu_1112_p1");
    sc_trace(mVcdFile, tmp_fu_1128_p2, "tmp_fu_1128_p2");
    sc_trace(mVcdFile, tmp_cast_fu_1120_p1, "tmp_cast_fu_1120_p1");
    sc_trace(mVcdFile, tmp_cast_14_fu_1124_p1, "tmp_cast_14_fu_1124_p1");
    sc_trace(mVcdFile, tmp1_fu_1138_p2, "tmp1_fu_1138_p2");
    sc_trace(mVcdFile, tmp184_cast_fu_1144_p1, "tmp184_cast_fu_1144_p1");
    sc_trace(mVcdFile, tmp183_cast_fu_1134_p1, "tmp183_cast_fu_1134_p1");
    sc_trace(mVcdFile, r_V_31_fu_1160_p0, "r_V_31_fu_1160_p0");
    sc_trace(mVcdFile, r_V_31_fu_1160_p1, "r_V_31_fu_1160_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_2_fu_1166_p1, "tmp_2_fu_1166_p1");
    sc_trace(mVcdFile, r_V_fu_1169_p2, "r_V_fu_1169_p2");
    sc_trace(mVcdFile, tmp_20_fu_1185_p4, "tmp_20_fu_1185_p4");
    sc_trace(mVcdFile, roundedNoise_V_fu_1175_p4, "roundedNoise_V_fu_1175_p4");
    sc_trace(mVcdFile, icmp_fu_1195_p2, "icmp_fu_1195_p2");
    sc_trace(mVcdFile, tmp_5_fu_1201_p2, "tmp_5_fu_1201_p2");
    sc_trace(mVcdFile, tmp_6_fu_1225_p2, "tmp_6_fu_1225_p2");
    sc_trace(mVcdFile, saturatedNoise_V_1_fu_1217_p3, "saturatedNoise_V_1_fu_1217_p3");
    sc_trace(mVcdFile, saturatedNoise_V_fu_1207_p4, "saturatedNoise_V_fu_1207_p4");
    sc_trace(mVcdFile, r_V_12_fu_1239_p0, "r_V_12_fu_1239_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, r_V_12_fu_1239_p00, "r_V_12_fu_1239_p00");
    sc_trace(mVcdFile, r_V_31_fu_1160_p10, "r_V_31_fu_1160_p10");
#endif

    }
}

operator_s::~operator_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete coarseContents_U;
    delete gradientContents_U;
    delete scaleLookup_U;
    delete norm_V_U;
    delete awgn_top_mux_42_9_1_U0;
    delete awgn_top_mul_mul_eOg_U1;
}

void operator_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        bramChapter_3_V_1_fu_140 = bramChapter_3_V_9_fu_811_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        bramChapter_3_V_1_fu_140 = bramChapter_0_V_1_fu_486_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        bramChapter_3_V_2_fu_144 = bramChapter_3_V_8_fu_804_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        bramChapter_3_V_2_fu_144 = bramChapter_1_V_1_fu_478_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        bramChapter_3_V_4_fu_148 = bramChapter_3_V_5_fu_790_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        bramChapter_3_V_4_fu_148 = newSel3_fu_462_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        bramChapter_3_V_fu_152 = bramChapter_3_V_3_fu_776_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        bramChapter_3_V_fu_152 = newSel1_fu_446_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        i_reg_283 = i_1_reg_1297.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_283 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        normStage_reg_294 = normStage_1_reg_1375.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        normStage_reg_294 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        centralLimitNoise_V_reg_1437 = centralLimitNoise_V_fu_1148_p2.read();
        scale_V_reg_1442 = scaleLookup_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        coarseContents_load_reg_1400 = coarseContents_q0.read();
        r_V_12_reg_1405 = r_V_12_fu_1239_p2.read();
        sel_tmp10_reg_1410 = sel_tmp10_fu_908_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        i_1_reg_1297 = i_1_fu_368_p2.read();
        tmp_8_reg_1287 = tmp_8_fu_351_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        noiseGen_3_V_2_reg_259 = noiseGen_3_V_3_fu_1088_p3.read();
        noiseGen_3_V_4_reg_271 = noiseGen_3_V_6_fu_1104_p3.read();
        noiseGen_V_2_reg_247 = noiseGen_3_V_1_fu_1050_p3.read();
        noiseGen_V_3_reg_235 = noiseGen_3_V_fu_1011_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        normStage_1_reg_1375 = normStage_1_fu_672_p2.read();
        normStage_cast_reg_1367 = normStage_cast_fu_662_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        or_cond_reg_1351 = or_cond_fu_432_p2.read();
        r_V_9_reg_1310 = r_V_9_fu_390_p2.read();
        sel_tmp1_reg_1333 = sel_tmp1_fu_420_p2.read();
        sel_tmp2_reg_1340 = sel_tmp2_fu_426_p2.read();
        sel_tmp_reg_1325 = sel_tmp_fu_414_p2.read();
        tmp_21_reg_1302 = tmp_21_fu_374_p1.read();
        tmp_22_reg_1316 = r_V_9_fu_390_p2.read().range(31, 31);
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_Val2_s_reg_1278 = uut_lfsr128_V.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        r_V_31_reg_1447 = r_V_31_fu_1160_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_666_p2.read()))) {
        tmp_23_reg_1382 = tmp_23_fu_697_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && !esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0))) {
        uut_lfsr128_V = p_Result_s_fu_630_p3.read();
    }
}

void operator_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void operator_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void operator_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void operator_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void operator_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void operator_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void operator_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void operator_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void operator_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void operator_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void operator_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void operator_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void operator_s::thread_ap_return() {
    ap_return = (!tmp_6_fu_1225_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_6_fu_1225_p2.read()[0].to_bool())? saturatedNoise_V_1_fu_1217_p3.read(): saturatedNoise_V_fu_1207_p4.read());
}

void operator_s::thread_bramChapter_0_V_1_fu_486_p3() {
    bramChapter_0_V_1_fu_486_p3 = (!sel_tmp2_fu_426_p2.read()[0].is_01())? sc_lv<9>(): ((sel_tmp2_fu_426_p2.read()[0].to_bool())? ap_const_lv9_0: bramChapter_3_V_1_fu_140.read());
}

void operator_s::thread_bramChapter_1_V_1_fu_478_p3() {
    bramChapter_1_V_1_fu_478_p3 = (!sel_tmp2_fu_426_p2.read()[0].is_01())? sc_lv<9>(): ((sel_tmp2_fu_426_p2.read()[0].to_bool())? bramChapter_3_V_2_fu_144.read(): sel_tmp3_fu_470_p3.read());
}

void operator_s::thread_bramChapter_3_V_10_fu_763_p2() {
    bramChapter_3_V_10_fu_763_p2 = (!r_V_16_fu_757_p2.read().is_01() || !grp_fu_318_p6.read().is_01())? sc_lv<9>(): (sc_biguint<9>(r_V_16_fu_757_p2.read()) + sc_biguint<9>(grp_fu_318_p6.read()));
}

void operator_s::thread_bramChapter_3_V_3_fu_776_p3() {
    bramChapter_3_V_3_fu_776_p3 = (!or_cond_reg_1351.read()[0].is_01())? sc_lv<9>(): ((or_cond_reg_1351.read()[0].to_bool())? bramChapter_3_V_fu_152.read(): newSel15_fu_769_p3.read());
}

void operator_s::thread_bramChapter_3_V_5_fu_790_p3() {
    bramChapter_3_V_5_fu_790_p3 = (!or_cond_reg_1351.read()[0].is_01())? sc_lv<9>(): ((or_cond_reg_1351.read()[0].to_bool())? bramChapter_3_V_4_fu_148.read(): newSel16_fu_783_p3.read());
}

void operator_s::thread_bramChapter_3_V_7_fu_797_p3() {
    bramChapter_3_V_7_fu_797_p3 = (!sel_tmp1_reg_1333.read()[0].is_01())? sc_lv<9>(): ((sel_tmp1_reg_1333.read()[0].to_bool())? bramChapter_3_V_10_fu_763_p2.read(): bramChapter_3_V_2_fu_144.read());
}

void operator_s::thread_bramChapter_3_V_8_fu_804_p3() {
    bramChapter_3_V_8_fu_804_p3 = (!sel_tmp2_reg_1340.read()[0].is_01())? sc_lv<9>(): ((sel_tmp2_reg_1340.read()[0].to_bool())? bramChapter_3_V_2_fu_144.read(): bramChapter_3_V_7_fu_797_p3.read());
}

void operator_s::thread_bramChapter_3_V_9_fu_811_p3() {
    bramChapter_3_V_9_fu_811_p3 = (!sel_tmp2_reg_1340.read()[0].is_01())? sc_lv<9>(): ((sel_tmp2_reg_1340.read()[0].to_bool())? bramChapter_3_V_10_fu_763_p2.read(): bramChapter_3_V_1_fu_140.read());
}

void operator_s::thread_centralLimitNoise_V_fu_1148_p2() {
    centralLimitNoise_V_fu_1148_p2 = (!tmp184_cast_fu_1144_p1.read().is_01() || !tmp183_cast_fu_1134_p1.read().is_01())? sc_lv<31>(): (sc_bigint<31>(tmp184_cast_fu_1144_p1.read()) + sc_bigint<31>(tmp183_cast_fu_1134_p1.read()));
}

void operator_s::thread_coarseContents_address0() {
    coarseContents_address0 =  (sc_lv<9>) (tmp_13_fu_700_p1.read());
}

void operator_s::thread_coarseContents_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        coarseContents_ce0 = ap_const_logic_1;
    } else {
        coarseContents_ce0 = ap_const_logic_0;
    }
}

void operator_s::thread_exitcond1_fu_362_p2() {
    exitcond1_fu_362_p2 = (!i_reg_283.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_283.read() == ap_const_lv3_4);
}

void operator_s::thread_exitcond_fu_666_p2() {
    exitcond_fu_666_p2 = (!normStage_reg_294.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(normStage_reg_294.read() == ap_const_lv3_4);
}

void operator_s::thread_gradientContents_address0() {
    gradientContents_address0 =  (sc_lv<9>) (tmp_13_fu_700_p1.read());
}

void operator_s::thread_gradientContents_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        gradientContents_ce0 = ap_const_logic_1;
    } else {
        gradientContents_ce0 = ap_const_logic_0;
    }
}

void operator_s::thread_i_1_fu_368_p2() {
    i_1_fu_368_p2 = (!i_reg_283.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_283.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void operator_s::thread_i_cast_cast_fu_335_p1() {
    i_cast_cast_fu_335_p1 = esl_zext<6,3>(i_reg_283.read());
}

void operator_s::thread_icmp_fu_1195_p2() {
    icmp_fu_1195_p2 = (!tmp_20_fu_1185_p4.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): (sc_bigint<4>(tmp_20_fu_1185_p4.read()) > sc_bigint<4>(ap_const_lv4_0));
}

void operator_s::thread_lfsr1_V_fu_514_p4() {
    lfsr1_V_fu_514_p4 = p_Val2_s_reg_1278.read().range(127, 64);
}

void operator_s::thread_lfsr2_V_fu_523_p1() {
    lfsr2_V_fu_523_p1 = p_Val2_s_reg_1278.read().range(64-1, 0);
}

void operator_s::thread_newSel10_fu_1042_p3() {
    newSel10_fu_1042_p3 = (!or_cond3_fu_985_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond3_fu_985_p2.read()[0].to_bool())? noiseGen_V_2_reg_247.read(): newSel9_fu_1027_p3.read());
}

void operator_s::thread_newSel11_fu_1058_p3() {
    newSel11_fu_1058_p3 = (!sel_tmp12_fu_959_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp12_fu_959_p2.read()[0].to_bool())? noiseGen_0_V_fu_928_p2.read(): noiseGen_3_V_2_reg_259.read());
}

void operator_s::thread_newSel12_fu_1066_p3() {
    newSel12_fu_1066_p3 = (!sel_tmp10_reg_1410.read()[0].is_01())? sc_lv<29>(): ((sel_tmp10_reg_1410.read()[0].to_bool())? noiseGen_3_V_2_reg_259.read(): noiseGen_0_V_2_fu_934_p2.read());
}

void operator_s::thread_newSel13_fu_1073_p3() {
    newSel13_fu_1073_p3 = (!sel_tmp2_reg_1340.read()[0].is_01())? sc_lv<29>(): ((sel_tmp2_reg_1340.read()[0].to_bool())? noiseGen_3_V_2_reg_259.read(): newSel11_fu_1058_p3.read());
}

void operator_s::thread_newSel14_fu_1080_p3() {
    newSel14_fu_1080_p3 = (!or_cond3_fu_985_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond3_fu_985_p2.read()[0].to_bool())? newSel12_fu_1066_p3.read(): noiseGen_3_V_2_reg_259.read());
}

void operator_s::thread_newSel15_fu_769_p3() {
    newSel15_fu_769_p3 = (!sel_tmp_reg_1325.read()[0].is_01())? sc_lv<9>(): ((sel_tmp_reg_1325.read()[0].to_bool())? bramChapter_3_V_fu_152.read(): bramChapter_3_V_10_fu_763_p2.read());
}

void operator_s::thread_newSel16_fu_783_p3() {
    newSel16_fu_783_p3 = (!sel_tmp_reg_1325.read()[0].is_01())? sc_lv<9>(): ((sel_tmp_reg_1325.read()[0].to_bool())? bramChapter_3_V_10_fu_763_p2.read(): bramChapter_3_V_4_fu_148.read());
}

void operator_s::thread_newSel1_fu_446_p3() {
    newSel1_fu_446_p3 = (!or_cond_fu_432_p2.read()[0].is_01())? sc_lv<9>(): ((or_cond_fu_432_p2.read()[0].to_bool())? bramChapter_3_V_fu_152.read(): newSel_fu_438_p3.read());
}

void operator_s::thread_newSel2_fu_454_p3() {
    newSel2_fu_454_p3 = (!sel_tmp_fu_414_p2.read()[0].is_01())? sc_lv<9>(): ((sel_tmp_fu_414_p2.read()[0].to_bool())? ap_const_lv9_0: bramChapter_3_V_4_fu_148.read());
}

void operator_s::thread_newSel3_fu_462_p3() {
    newSel3_fu_462_p3 = (!or_cond_fu_432_p2.read()[0].is_01())? sc_lv<9>(): ((or_cond_fu_432_p2.read()[0].to_bool())? bramChapter_3_V_4_fu_148.read(): newSel2_fu_454_p3.read());
}

void operator_s::thread_newSel4_fu_978_p3() {
    newSel4_fu_978_p3 = (!sel_tmp10_reg_1410.read()[0].is_01())? sc_lv<29>(): ((sel_tmp10_reg_1410.read()[0].to_bool())? noiseGen_0_V_fu_928_p2.read(): noiseGen_V_3_reg_235.read());
}

void operator_s::thread_newSel5_fu_990_p3() {
    newSel5_fu_990_p3 = (!sel_tmp5_fu_945_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp5_fu_945_p2.read()[0].to_bool())? noiseGen_V_3_reg_235.read(): noiseGen_0_V_2_fu_934_p2.read());
}

void operator_s::thread_newSel6_fu_1003_p3() {
    newSel6_fu_1003_p3 = (!or_cond3_fu_985_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond3_fu_985_p2.read()[0].to_bool())? newSel4_fu_978_p3.read(): newSel5_fu_990_p3.read());
}

void operator_s::thread_newSel7_fu_1035_p3() {
    newSel7_fu_1035_p3 = (!sel_tmp2_reg_1340.read()[0].is_01())? sc_lv<29>(): ((sel_tmp2_reg_1340.read()[0].to_bool())? noiseGen_V_2_reg_247.read(): newSel8_fu_1019_p3.read());
}

void operator_s::thread_newSel8_fu_1019_p3() {
    newSel8_fu_1019_p3 = (!sel_tmp12_fu_959_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp12_fu_959_p2.read()[0].to_bool())? noiseGen_V_2_reg_247.read(): noiseGen_0_V_fu_928_p2.read());
}

void operator_s::thread_newSel9_fu_1027_p3() {
    newSel9_fu_1027_p3 = (!sel_tmp5_fu_945_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp5_fu_945_p2.read()[0].to_bool())? noiseGen_0_V_2_fu_934_p2.read(): noiseGen_V_2_reg_247.read());
}

void operator_s::thread_newSel_fu_438_p3() {
    newSel_fu_438_p3 = (!sel_tmp_fu_414_p2.read()[0].is_01())? sc_lv<9>(): ((sel_tmp_fu_414_p2.read()[0].to_bool())? bramChapter_3_V_fu_152.read(): ap_const_lv9_0);
}

void operator_s::thread_noiseGen_0_V_2_fu_934_p2() {
    noiseGen_0_V_2_fu_934_p2 = (!r_V_11_cast_fu_924_p1.read().is_01() || !tmp_14_fu_914_p1.read().is_01())? sc_lv<29>(): (sc_biguint<29>(r_V_11_cast_fu_924_p1.read()) + sc_bigint<29>(tmp_14_fu_914_p1.read()));
}

void operator_s::thread_noiseGen_0_V_fu_928_p2() {
    noiseGen_0_V_fu_928_p2 = (!tmp_14_fu_914_p1.read().is_01() || !r_V_11_cast_fu_924_p1.read().is_01())? sc_lv<29>(): (sc_bigint<29>(tmp_14_fu_914_p1.read()) - sc_biguint<29>(r_V_11_cast_fu_924_p1.read()));
}

void operator_s::thread_noiseGen_3_V_1_fu_1050_p3() {
    noiseGen_3_V_1_fu_1050_p3 = (!or_cond4_fu_998_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond4_fu_998_p2.read()[0].to_bool())? newSel7_fu_1035_p3.read(): newSel10_fu_1042_p3.read());
}

void operator_s::thread_noiseGen_3_V_3_fu_1088_p3() {
    noiseGen_3_V_3_fu_1088_p3 = (!or_cond4_fu_998_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond4_fu_998_p2.read()[0].to_bool())? newSel13_fu_1073_p3.read(): newSel14_fu_1080_p3.read());
}

void operator_s::thread_noiseGen_3_V_5_fu_1096_p3() {
    noiseGen_3_V_5_fu_1096_p3 = (!sel_tmp13_fu_963_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp13_fu_963_p2.read()[0].to_bool())? noiseGen_0_V_2_fu_934_p2.read(): noiseGen_3_V_4_reg_271.read());
}

void operator_s::thread_noiseGen_3_V_6_fu_1104_p3() {
    noiseGen_3_V_6_fu_1104_p3 = (!sel_tmp14_fu_968_p2.read()[0].is_01())? sc_lv<29>(): ((sel_tmp14_fu_968_p2.read()[0].to_bool())? noiseGen_0_V_fu_928_p2.read(): noiseGen_3_V_5_fu_1096_p3.read());
}

void operator_s::thread_noiseGen_3_V_fu_1011_p3() {
    noiseGen_3_V_fu_1011_p3 = (!or_cond4_fu_998_p2.read()[0].is_01())? sc_lv<29>(): ((or_cond4_fu_998_p2.read()[0].to_bool())? noiseGen_V_3_reg_235.read(): newSel6_fu_1003_p3.read());
}

void operator_s::thread_normStage_1_fu_672_p2() {
    normStage_1_fu_672_p2 = (!normStage_reg_294.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(normStage_reg_294.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void operator_s::thread_normStage_cast1_cast_fu_648_p1() {
    normStage_cast1_cast_fu_648_p1 = esl_zext<6,3>(normStage_reg_294.read());
}

void operator_s::thread_normStage_cast_fu_662_p1() {
    normStage_cast_fu_662_p1 = esl_zext<4,3>(normStage_reg_294.read());
}

void operator_s::thread_norm_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        norm_V_address0 =  (sc_lv<5>) (tmp_27_cast_fu_859_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        norm_V_address0 =  (sc_lv<5>) (tmp_28_cast_fu_826_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        norm_V_address0 =  (sc_lv<5>) (tmp_26_cast_fu_657_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        norm_V_address0 =  (sc_lv<5>) (tmp_8_cast_fu_357_p1.read());
    } else {
        norm_V_address0 = "XXXXX";
    }
}

void operator_s::thread_norm_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read())))) {
        norm_V_ce0 = ap_const_logic_1;
    } else {
        norm_V_ce0 = ap_const_logic_0;
    }
}

void operator_s::thread_norm_V_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        norm_V_d0 = r_V_15_fu_868_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read()))) {
        norm_V_d0 = norm_V_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        norm_V_d0 = r_V_9_fu_390_p2.read().range(29, 15);
    } else {
        norm_V_d0 =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
    }
}

void operator_s::thread_norm_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, phitmp4_fu_742_p2.read())))) {
        norm_V_we0 = ap_const_logic_1;
    } else {
        norm_V_we0 = ap_const_logic_0;
    }
}

void operator_s::thread_op2_assign_1_cast_fu_728_p1() {
    op2_assign_1_cast_fu_728_p1 = esl_zext<15,4>(op2_assign_1_fu_722_p2.read());
}

void operator_s::thread_op2_assign_1_fu_722_p2() {
    op2_assign_1_fu_722_p2 = (r_V_14_fu_716_p2.read() ^ ap_const_lv4_F);
}

void operator_s::thread_op2_assign_2_cast_fu_712_p1() {
    op2_assign_2_cast_fu_712_p1 = esl_zext<4,3>(op2_assign_2_fu_706_p2.read());
}

void operator_s::thread_op2_assign_2_fu_706_p2() {
    op2_assign_2_fu_706_p2 = (!ap_const_lv3_3.is_01() || !normStage_reg_294.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_3) - sc_biguint<3>(normStage_reg_294.read()));
}

void operator_s::thread_op2_assign_3_cast_fu_753_p1() {
    op2_assign_3_cast_fu_753_p1 = esl_zext<9,4>(op2_assign_3_fu_748_p2.read());
}

void operator_s::thread_op2_assign_3_fu_748_p2() {
    op2_assign_3_fu_748_p2 = (!ap_const_lv4_8.is_01() || !normStage_cast_reg_1367.read().is_01())? sc_lv<4>(): (sc_bigint<4>(ap_const_lv4_8) - sc_biguint<4>(normStage_cast_reg_1367.read()));
}

void operator_s::thread_op2_assign_fu_378_p3() {
    op2_assign_fu_378_p3 = esl_concat<2,5>(tmp_21_fu_374_p1.read(), ap_const_lv5_0);
}

void operator_s::thread_or_cond2_fu_972_p2() {
    or_cond2_fu_972_p2 = (sel_tmp12_fu_959_p2.read() | sel_tmp11_fu_955_p2.read());
}

void operator_s::thread_or_cond3_fu_985_p2() {
    or_cond3_fu_985_p2 = (sel_tmp10_reg_1410.read() | sel_tmp6_fu_950_p2.read());
}

void operator_s::thread_or_cond4_fu_998_p2() {
    or_cond4_fu_998_p2 = (sel_tmp2_reg_1340.read() | or_cond2_fu_972_p2.read());
}

void operator_s::thread_or_cond_fu_432_p2() {
    or_cond_fu_432_p2 = (sel_tmp2_fu_426_p2.read() | sel_tmp1_fu_420_p2.read());
}

void operator_s::thread_p_2_cast_fu_1112_p1() {
    p_2_cast_fu_1112_p1 = esl_sext<30,29>(noiseGen_3_V_4_reg_271.read());
}

void operator_s::thread_p_3_cast_fu_1116_p1() {
    p_3_cast_fu_1116_p1 = esl_sext<30,29>(noiseGen_3_V_2_reg_259.read());
}

void operator_s::thread_p_Result_s_fu_630_p3() {
    p_Result_s_fu_630_p3 = esl_concat<64,64>(r_V_24_fu_575_p2.read(), r_V_30_fu_624_p2.read());
}

void operator_s::thread_p_shl_cast_fu_347_p1() {
    p_shl_cast_fu_347_p1 = esl_zext<6,5>(tmp_3_fu_339_p3.read());
}

void operator_s::thread_phitmp2_fu_678_p4() {
    phitmp2_fu_678_p4 = r_V_9_reg_1310.read().range(14, 10);
}

void operator_s::thread_phitmp4_fu_742_p2() {
    phitmp4_fu_742_p2 = (!tmp_24_fu_738_p1.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_fu_738_p1.read() == ap_const_lv9_0);
}

void operator_s::thread_r_V_11_cast_fu_924_p1() {
    r_V_11_cast_fu_924_p1 = esl_zext<29,27>(r_V_13_fu_917_p3.read());
}

void operator_s::thread_r_V_12_fu_1239_p0() {
    r_V_12_fu_1239_p0 =  (sc_lv<13>) (r_V_12_fu_1239_p00.read());
}

void operator_s::thread_r_V_12_fu_1239_p00() {
    r_V_12_fu_1239_p00 = esl_zext<23,13>(gradientContents_q0.read());
}

void operator_s::thread_r_V_13_fu_917_p3() {
    r_V_13_fu_917_p3 = esl_concat<17,10>(coarseContents_load_reg_1400.read(), ap_const_lv10_0);
}

void operator_s::thread_r_V_14_fu_716_p2() {
    r_V_14_fu_716_p2 = (!op2_assign_2_cast_fu_712_p1.read().is_01())? sc_lv<4>(): ap_const_lv4_1 << (unsigned short)op2_assign_2_cast_fu_712_p1.read().to_uint();
}

void operator_s::thread_r_V_15_fu_868_p2() {
    r_V_15_fu_868_p2 = (!tmp_39_cast_fu_864_p1.read().is_01())? sc_lv<15>(): norm_V_q0.read() << (unsigned short)tmp_39_cast_fu_864_p1.read().to_uint();
}

void operator_s::thread_r_V_16_fu_757_p2() {
    r_V_16_fu_757_p2 = (!op2_assign_3_cast_fu_753_p1.read().is_01())? sc_lv<9>(): ap_const_lv9_1 << (unsigned short)op2_assign_3_cast_fu_753_p1.read().to_uint();
}

void operator_s::thread_r_V_19_fu_535_p3() {
    r_V_19_fu_535_p3 = esl_concat<30,34>(tmp_9_fu_526_p4.read(), ap_const_lv34_0);
}

void operator_s::thread_r_V_20_fu_543_p2() {
    r_V_20_fu_543_p2 = (r_V_19_fu_535_p3.read() ^ lfsr1_V_fu_514_p4.read());
}

void operator_s::thread_r_V_21_fu_559_p1() {
    r_V_21_fu_559_p1 = esl_zext<64,29>(r_V_s_fu_549_p4.read());
}

void operator_s::thread_r_V_22_fu_563_p2() {
    r_V_22_fu_563_p2 = (r_V_21_fu_559_p1.read() ^ r_V_20_fu_543_p2.read());
}

void operator_s::thread_r_V_23_fu_569_p2() {
    r_V_23_fu_569_p2 = (!ap_const_lv64_1.is_01())? sc_lv<64>(): r_V_22_fu_563_p2.read() << (unsigned short)ap_const_lv64_1.to_uint();
}

void operator_s::thread_r_V_24_fu_575_p2() {
    r_V_24_fu_575_p2 = (r_V_23_fu_569_p2.read() ^ r_V_22_fu_563_p2.read());
}

void operator_s::thread_r_V_25_fu_584_p3() {
    r_V_25_fu_584_p3 = esl_concat<6,58>(tmp_18_fu_581_p1.read(), ap_const_lv58_0);
}

void operator_s::thread_r_V_26_fu_592_p2() {
    r_V_26_fu_592_p2 = (r_V_25_fu_584_p3.read() ^ lfsr2_V_fu_523_p1.read());
}

void operator_s::thread_r_V_27_fu_608_p1() {
    r_V_27_fu_608_p1 = esl_zext<64,51>(r_V_6_fu_598_p4.read());
}

void operator_s::thread_r_V_28_fu_612_p2() {
    r_V_28_fu_612_p2 = (r_V_27_fu_608_p1.read() ^ r_V_26_fu_592_p2.read());
}

void operator_s::thread_r_V_29_fu_618_p2() {
    r_V_29_fu_618_p2 = (!ap_const_lv64_7.is_01())? sc_lv<64>(): r_V_28_fu_612_p2.read() << (unsigned short)ap_const_lv64_7.to_uint();
}

void operator_s::thread_r_V_30_fu_624_p2() {
    r_V_30_fu_624_p2 = (r_V_29_fu_618_p2.read() ^ r_V_28_fu_612_p2.read());
}

void operator_s::thread_r_V_31_fu_1160_p0() {
    r_V_31_fu_1160_p0 = centralLimitNoise_V_reg_1437.read();
}

void operator_s::thread_r_V_31_fu_1160_p1() {
    r_V_31_fu_1160_p1 =  (sc_lv<17>) (r_V_31_fu_1160_p10.read());
}

void operator_s::thread_r_V_31_fu_1160_p10() {
    r_V_31_fu_1160_p10 = esl_zext<48,17>(scale_V_reg_1442.read());
}

void operator_s::thread_r_V_31_fu_1160_p2() {
    r_V_31_fu_1160_p2 = (!r_V_31_fu_1160_p0.read().is_01() || !r_V_31_fu_1160_p1.read().is_01())? sc_lv<48>(): sc_bigint<31>(r_V_31_fu_1160_p0.read()) * sc_biguint<17>(r_V_31_fu_1160_p1.read());
}

void operator_s::thread_r_V_6_fu_598_p4() {
    r_V_6_fu_598_p4 = r_V_26_fu_592_p2.read().range(63, 13);
}

void operator_s::thread_r_V_9_fu_390_p2() {
    r_V_9_fu_390_p2 = (!tmp_7_fu_386_p1.read().is_01())? sc_lv<128>(): p_Val2_s_reg_1278.read() >> (unsigned short)tmp_7_fu_386_p1.read().to_uint();
}

void operator_s::thread_r_V_fu_1169_p2() {
    r_V_fu_1169_p2 = (!ap_const_lv49_10000000.is_01() || !tmp_2_fu_1166_p1.read().is_01())? sc_lv<49>(): (sc_biguint<49>(ap_const_lv49_10000000) + sc_biguint<49>(tmp_2_fu_1166_p1.read()));
}

void operator_s::thread_r_V_s_fu_549_p4() {
    r_V_s_fu_549_p4 = r_V_20_fu_543_p2.read().range(63, 35);
}

void operator_s::thread_roundedNoise_V_fu_1175_p4() {
    roundedNoise_V_fu_1175_p4 = r_V_fu_1169_p2.read().range(47, 29);
}

void operator_s::thread_saturatedNoise_V_1_fu_1217_p3() {
    saturatedNoise_V_1_fu_1217_p3 = (!icmp_fu_1195_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_fu_1195_p2.read()[0].to_bool())? ap_const_lv16_7FFF: ap_const_lv16_8001);
}

void operator_s::thread_saturatedNoise_V_fu_1207_p4() {
    saturatedNoise_V_fu_1207_p4 = r_V_fu_1169_p2.read().range(44, 29);
}

void operator_s::thread_scaleLookup_address0() {
    scaleLookup_address0 =  (sc_lv<8>) (tmp_s_fu_644_p1.read());
}

void operator_s::thread_scaleLookup_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        scaleLookup_ce0 = ap_const_logic_1;
    } else {
        scaleLookup_ce0 = ap_const_logic_0;
    }
}

void operator_s::thread_sel_tmp10_fu_908_p2() {
    sel_tmp10_fu_908_p2 = (tmp13_fu_903_p2.read() & tmp12_fu_897_p2.read());
}

void operator_s::thread_sel_tmp11_fu_955_p2() {
    sel_tmp11_fu_955_p2 = (tmp_22_reg_1316.read() & sel_tmp_reg_1325.read());
}

void operator_s::thread_sel_tmp12_fu_959_p2() {
    sel_tmp12_fu_959_p2 = (tmp_22_reg_1316.read() & sel_tmp1_reg_1333.read());
}

void operator_s::thread_sel_tmp13_fu_963_p2() {
    sel_tmp13_fu_963_p2 = (sel_tmp2_reg_1340.read() & sel_tmp4_fu_940_p2.read());
}

void operator_s::thread_sel_tmp14_fu_968_p2() {
    sel_tmp14_fu_968_p2 = (tmp_22_reg_1316.read() & sel_tmp2_reg_1340.read());
}

void operator_s::thread_sel_tmp1_fu_420_p2() {
    sel_tmp1_fu_420_p2 = (!tmp_21_fu_374_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_fu_374_p1.read() == ap_const_lv2_1);
}

void operator_s::thread_sel_tmp2_fu_426_p2() {
    sel_tmp2_fu_426_p2 = (!tmp_21_fu_374_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_fu_374_p1.read() == ap_const_lv2_0);
}

void operator_s::thread_sel_tmp3_fu_470_p3() {
    sel_tmp3_fu_470_p3 = (!sel_tmp1_fu_420_p2.read()[0].is_01())? sc_lv<9>(): ((sel_tmp1_fu_420_p2.read()[0].to_bool())? ap_const_lv9_0: bramChapter_3_V_2_fu_144.read());
}

void operator_s::thread_sel_tmp4_fu_940_p2() {
    sel_tmp4_fu_940_p2 = (tmp_22_reg_1316.read() ^ ap_const_lv1_1);
}

void operator_s::thread_sel_tmp5_fu_945_p2() {
    sel_tmp5_fu_945_p2 = (sel_tmp_reg_1325.read() & sel_tmp4_fu_940_p2.read());
}

void operator_s::thread_sel_tmp6_fu_950_p2() {
    sel_tmp6_fu_950_p2 = (sel_tmp1_reg_1333.read() & sel_tmp4_fu_940_p2.read());
}

void operator_s::thread_sel_tmp7_fu_882_p2() {
    sel_tmp7_fu_882_p2 = (!tmp_21_reg_1302.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_reg_1302.read() != ap_const_lv2_0);
}

void operator_s::thread_sel_tmp8_fu_887_p2() {
    sel_tmp8_fu_887_p2 = (!tmp_21_reg_1302.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_reg_1302.read() != ap_const_lv2_1);
}

void operator_s::thread_sel_tmp9_fu_892_p2() {
    sel_tmp9_fu_892_p2 = (!tmp_21_reg_1302.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_reg_1302.read() != ap_const_lv2_2);
}

void operator_s::thread_sel_tmp_fu_414_p2() {
    sel_tmp_fu_414_p2 = (!tmp_21_fu_374_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_21_fu_374_p1.read() == ap_const_lv2_2);
}

void operator_s::thread_tmp12_fu_897_p2() {
    tmp12_fu_897_p2 = (sel_tmp7_fu_882_p2.read() & sel_tmp8_fu_887_p2.read());
}

void operator_s::thread_tmp13_fu_903_p2() {
    tmp13_fu_903_p2 = (tmp_22_reg_1316.read() & sel_tmp9_fu_892_p2.read());
}

void operator_s::thread_tmp183_cast_fu_1134_p1() {
    tmp183_cast_fu_1134_p1 = esl_sext<31,30>(tmp_fu_1128_p2.read());
}

void operator_s::thread_tmp184_cast_fu_1144_p1() {
    tmp184_cast_fu_1144_p1 = esl_sext<31,30>(tmp1_fu_1138_p2.read());
}

void operator_s::thread_tmp1_fu_1138_p2() {
    tmp1_fu_1138_p2 = (!tmp_cast_fu_1120_p1.read().is_01() || !tmp_cast_14_fu_1124_p1.read().is_01())? sc_lv<30>(): (sc_bigint<30>(tmp_cast_fu_1120_p1.read()) + sc_bigint<30>(tmp_cast_14_fu_1124_p1.read()));
}

void operator_s::thread_tmp_11_fu_687_p1() {
    tmp_11_fu_687_p1 = esl_zext<9,5>(phitmp2_fu_678_p4.read());
}

void operator_s::thread_tmp_12_fu_691_p2() {
    tmp_12_fu_691_p2 = (!grp_fu_318_p6.read().is_01() || !tmp_11_fu_687_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(grp_fu_318_p6.read()) + sc_biguint<9>(tmp_11_fu_687_p1.read()));
}

void operator_s::thread_tmp_13_fu_700_p1() {
    tmp_13_fu_700_p1 = esl_zext<32,9>(tmp_12_fu_691_p2.read());
}

void operator_s::thread_tmp_14_fu_914_p1() {
    tmp_14_fu_914_p1 = esl_sext<29,23>(r_V_12_reg_1405.read());
}

void operator_s::thread_tmp_15_fu_732_p2() {
    tmp_15_fu_732_p2 = (!op2_assign_1_cast_fu_728_p1.read().is_01())? sc_lv<15>(): norm_V_q0.read() >> (unsigned short)op2_assign_1_cast_fu_728_p1.read().to_uint();
}

void operator_s::thread_tmp_16_fu_854_p2() {
    tmp_16_fu_854_p2 = (!tmp_8_reg_1287.read().is_01() || !tmp_38_cast_cast_fu_851_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_reg_1287.read()) + sc_biguint<6>(tmp_38_cast_cast_fu_851_p1.read()));
}

void operator_s::thread_tmp_18_fu_581_p1() {
    tmp_18_fu_581_p1 = p_Val2_s_reg_1278.read().range(6-1, 0);
}

void operator_s::thread_tmp_19_fu_821_p2() {
    tmp_19_fu_821_p2 = (!tmp_8_reg_1287.read().is_01() || !tmp_42_cast_cast_fu_818_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_reg_1287.read()) + sc_biguint<6>(tmp_42_cast_cast_fu_818_p1.read()));
}

void operator_s::thread_tmp_20_fu_1185_p4() {
    tmp_20_fu_1185_p4 = r_V_fu_1169_p2.read().range(47, 44);
}

void operator_s::thread_tmp_21_fu_374_p1() {
    tmp_21_fu_374_p1 = i_reg_283.read().range(2-1, 0);
}

void operator_s::thread_tmp_23_fu_697_p1() {
    tmp_23_fu_697_p1 = r_V_9_reg_1310.read().range(10-1, 0);
}

void operator_s::thread_tmp_24_fu_738_p1() {
    tmp_24_fu_738_p1 = tmp_15_fu_732_p2.read().range(9-1, 0);
}

void operator_s::thread_tmp_26_cast_fu_657_p1() {
    tmp_26_cast_fu_657_p1 = esl_zext<32,6>(tmp_4_fu_652_p2.read());
}

void operator_s::thread_tmp_27_cast_fu_859_p1() {
    tmp_27_cast_fu_859_p1 = esl_zext<32,6>(tmp_16_fu_854_p2.read());
}

void operator_s::thread_tmp_28_cast_fu_826_p1() {
    tmp_28_cast_fu_826_p1 = esl_zext<32,6>(tmp_19_fu_821_p2.read());
}

void operator_s::thread_tmp_2_fu_1166_p1() {
    tmp_2_fu_1166_p1 = esl_zext<49,48>(r_V_31_reg_1447.read());
}

void operator_s::thread_tmp_38_cast_cast_fu_851_p1() {
    tmp_38_cast_cast_fu_851_p1 = esl_zext<6,3>(normStage_1_reg_1375.read());
}

void operator_s::thread_tmp_39_cast_fu_864_p1() {
    tmp_39_cast_fu_864_p1 = esl_zext<15,4>(r_V_14_fu_716_p2.read());
}

void operator_s::thread_tmp_3_fu_339_p3() {
    tmp_3_fu_339_p3 = esl_concat<3,2>(i_reg_283.read(), ap_const_lv2_0);
}

void operator_s::thread_tmp_42_cast_cast_fu_818_p1() {
    tmp_42_cast_cast_fu_818_p1 = esl_zext<6,3>(normStage_1_reg_1375.read());
}

void operator_s::thread_tmp_4_fu_652_p2() {
    tmp_4_fu_652_p2 = (!tmp_8_reg_1287.read().is_01() || !normStage_cast1_cast_fu_648_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_8_reg_1287.read()) + sc_biguint<6>(normStage_cast1_cast_fu_648_p1.read()));
}

void operator_s::thread_tmp_5_fu_1201_p2() {
    tmp_5_fu_1201_p2 = (!roundedNoise_V_fu_1175_p4.read().is_01() || !ap_const_lv19_78001.is_01())? sc_lv<1>(): (sc_bigint<19>(roundedNoise_V_fu_1175_p4.read()) < sc_bigint<19>(ap_const_lv19_78001));
}

void operator_s::thread_tmp_6_fu_1225_p2() {
    tmp_6_fu_1225_p2 = (icmp_fu_1195_p2.read() | tmp_5_fu_1201_p2.read());
}

void operator_s::thread_tmp_7_fu_386_p1() {
    tmp_7_fu_386_p1 = esl_zext<128,7>(op2_assign_fu_378_p3.read());
}

void operator_s::thread_tmp_8_cast_fu_357_p1() {
    tmp_8_cast_fu_357_p1 = esl_zext<32,6>(tmp_8_fu_351_p2.read());
}

void operator_s::thread_tmp_8_fu_351_p2() {
    tmp_8_fu_351_p2 = (!i_cast_cast_fu_335_p1.read().is_01() || !p_shl_cast_fu_347_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(i_cast_cast_fu_335_p1.read()) + sc_biguint<6>(p_shl_cast_fu_347_p1.read()));
}

void operator_s::thread_tmp_9_fu_526_p4() {
    tmp_9_fu_526_p4 = p_Val2_s_reg_1278.read().range(93, 64);
}

void operator_s::thread_tmp_cast_14_fu_1124_p1() {
    tmp_cast_14_fu_1124_p1 = esl_sext<30,29>(noiseGen_V_3_reg_235.read());
}

void operator_s::thread_tmp_cast_fu_1120_p1() {
    tmp_cast_fu_1120_p1 = esl_sext<30,29>(noiseGen_V_2_reg_247.read());
}

void operator_s::thread_tmp_fu_1128_p2() {
    tmp_fu_1128_p2 = (!p_3_cast_fu_1116_p1.read().is_01() || !p_2_cast_fu_1112_p1.read().is_01())? sc_lv<30>(): (sc_bigint<30>(p_3_cast_fu_1116_p1.read()) + sc_bigint<30>(p_2_cast_fu_1112_p1.read()));
}

void operator_s::thread_tmp_s_fu_644_p1() {
    tmp_s_fu_644_p1 = esl_zext<32,8>(snr_V_read.read());
}

void operator_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond1_fu_362_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_666_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

